### ISSUE TITLE
Trouble running example: ERROR webauthn_rs_core::core: Credential counter is 0

### ISSUE THREAD

**Issue by r3h0** [kanidm/webauthn-rs#125]
I like the look of this library! I ran into some trouble running the example (examples?).

First, there doesn't appear to be any examples defined in the `Cargo.toml` files, and the [documented command, `cargo run --example tide`](https://github.com/kanidm/webauthn-rs/tree/e423c5f9fca3378d12fdeb5b527ac7d9bfb4f695/webauthn-rs-demo#how-to-run-it) fails. After some digging and trial & error with the CLI flags, I ended up running this: `cargo run --release -- --bind=0.0.0.0:3000 --origin=https://test.com --id=test.com --name=test.com` with my real dev domain in place of `test.com`.

With the demo server running, I can now get to the demo page, enter a username, and hit the "register" button. This starts the FIDO2 auth flow (I assume) and my browser (Firefox on Ubuntu 20.04) prompts me:

> test.com wants to register an account with one of your security keys. You can connect and authorize one now, or cancel.

As soon as I touch my Yubikey 5 to activate it, the browser prompt disappears and the server logs show this error:

> ERROR webauthn_rs_core::core: Credential counter is 0 - may indicate that it is a passkey and not bound to hardware.

I can confirm that FIDO2 is enabled on the device, according to Yubikey Manager.

![image](https://user-images.githubusercontent.com/4955008/163415518-aa0629ad-b602-42d8-88ec-e5c5109286b8.png)

I tried changing `experimental_allow_passkeys` from `false` to `true`, but either I didn't change it in the right place, or there's some other issue -- possibly with the UI?

[Release v0.3.2](https://github.com/kanidm/webauthn-rs/releases/tag/v0.3.2) seems to work, so I'll roll with that for now.

**Comment by Firstyear** [comment]
No problem! Thanks for raising the issue. Mostly, the docs you are reading were referencing 0.3.2, and we've done a huge rearchitecture of the library recently. So if possibl/e, do try to target latest git as we want to release soon and the api will change a lot.

It's curious the issue you are seeing with the passkeys, since the demo site by default should ALLOW them. What model of device are you using?

**Comment by Firstyear** [comment]
Okay, I took a look and it appears to not be an issue with the authenticator, but a bug in firefox not handling the wasm of the demo page properly.

**Comment by Firstyear** [comment]
Narrowed it down to an issue with the wasm fetch api on firefox. Not sure how to progress from here though :(

**Comment by Firstyear** [comment]
Okay, resolved the wasm issue and the cred counter issue, both are going into #126 :)
