### ISSUE TITLE
Tutorial needed

### ISSUE THREAD

**Issue by ola-ct** [kanidm/webauthn-rs#127]
Please provide a tutorial that tells developers how to use your lib. I think many devs need something easier comprehensible than https://github.com/kanidm/webauthn-rs/tree/master/webauthn-rs-demo to dive into your lib. It's worth it ;-)

**Comment by Firstyear** [comment]
Thanks @ola-ct I'll try to work on this today. We've been reworking the library structure lately, but I'll sink some time into the docs of the main library.

**Comment by Firstyear** [comment]
@ola-ct Do you actually want a tutorial? Or just a super-minimal example site instead of the demo-site (which does quite a bit more).

Alternately, could a refactor of the demo site clarify things?

**Comment by ola-ct** [comment]
A context-free minimal tutorial would be nice, explaining things like "call this to achieve that, call that to achieve this". By "context-free" I mean that the example chosen should not depend on a certain infrastructure. The current example depends on `tide`. If you don't know `tide` you're almost lost ;-) The tutorial should be accompanied by functional code. TIA!

**Comment by Firstyear** [comment]
👍 Okay, will do today then :)

**Comment by ola-ct** [comment]
Thanks a lot, @Firstyear! 👍  That'll help :-)
