### ISSUE TITLE
webauthn client library

### ISSUE THREAD

**Issue by dvc94ch** [kanidm/webauthn-rs#134]
looks like there are the following "methods":

1. use CTAP directly (webauthn-rs-authenticator seems to be doing this, probably the way to go on desktop)
2. use the browser client api (there is an example in the tutorial)
3. use the android fido2 client api
4. use the ios passkeys client api??

It seems like it would be beneficial to have some kind of abstraction layer for these different client apis.

- https://developers.google.com/identity/fido/android/native-apps
- https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys

**Comment by Firstyear** [comment]
Might be worth pointing out, this library is mainly focused on being the *server* side of webauthn, not the *client* side. If you are making an ios app, you would call the apple passkey apis as above from within your app, and theywould send to the webauthn-rs server which validates those assertions/authentications.

**Comment by dvc94ch** [comment]
Started implementing this myself. Basically I need a crate that abstracts over the various platform apis and looks something like this:

```rust
use crate::platform::PlatformAuthenticator;
use anyhow::Result;
use webauthn_rs_proto::{
    CreationChallengeResponse, PublicKeyCredential, RegisterPublicKeyCredential,
    RequestChallengeResponse,
};

#[cfg(target_os = "android")]
#[path = "android.rs"]
mod platform;
#[cfg(any(target_os = "ios", target_os = "macos"))]
#[path = "passkey.rs"]
mod platform;
#[cfg(target_family = "wasm")]
#[path = "webauthn.rs"]
mod platform;
#[cfg(target_os = "windows")]
#[path = "hello.rs"]
mod platform;
#[cfg(not(any(
    target_os = "android",
    target_os = "ios",
    target_os = "macos",
    target_family = "wasm",
    target_os = "windows",
)))]
#[path = "u2fsoft.rs"]
mod platform;

pub struct Authenticator {
    platform: PlatformAuthenticator,
}

impl Authenticator {
    pub fn new() -> Self {
        Self {
            platform: PlatformAuthenticator::new(),
        }
    }

    pub async fn register(
        &self,
        origin: &str,
        ccr: CreationChallengeResponse,
    ) -> Result<RegisterPublicKeyCredential> {
        self.platform.register(origin, ccr).await
    }

    pub async fn authenticate(
        &self,
        origin: &str,
        rcr: RequestChallengeResponse,
    ) -> Result<PublicKeyCredential> {
        self.platform.authenticate(origin, rcr).await
    }
}
```

used your examples to build the u2fsoft and webauthn backends, but I plan to add support for the android fido2 and apple passkey apis.

**Comment by Firstyear** [comment]
Ahhhh I see. So you are effectively adding extra transports to webauthn-rs-authenticator then I assume? That would be VERY welcome!

**Comment by dvc94ch** [comment]
for now I'm playing around with it in a private repo. as soon as there is something useful, I'll make a PR. the reason why I though the authenticator crate has a slightly different scope is because you need to choose the transport at compile time. I'm currently using it as a fallback, but I think it will need some logic to detect the available tokens and select one. But it seems like all platforms except linux have some kind of an api that abstracts over whatever is available and selects the best option.

**Comment by Firstyear** [comment]
Nah, the only reason to "enable" or "disable" the apis, similar to features, is for CI, becuse when you go to do a challenge, on linux you need udev and other things. So we disable eveything but softtokens in CI cases so we can simulate webauthn in other projects.

But there is no reason NOT to have the other platforms available in webauthn-rs-authenticator, especially given that we want to enable different types of authenticators, especially the touchid case for macOS which I've been thinking to add recently .....

**Comment by benwis** [comment]
I'm also looking at this, but perhaps in a more limited sense. I want to handle the html myself, and perhaps have wasm do the data processing. Basically the tutorial client without yew that takes input.

**Comment by Firstyear** [comment]
@benwis There are already wasm binds to do all the transforms from the web_sys types to the webauthn-rs types. This issue/ticket is about interacting with authenticators on the client, where you are wanting the js-wasm elements that run in the browser. 

Take a look at:

https://github.com/kanidm/webauthn-rs/blob/master/webauthn-rs-proto/src/auth.rs#L76

For example.

**Comment by Firstyear** [comment]
We have authenticator rs built in now, and we have other client parts, so I'm closing this in favour of more specific issues if they exist.
