### ISSUE TITLE
WebauthnBuilder and prelude don't exist

### ISSUE THREAD

**Issue by benwis** [kanidm/webauthn-rs#147]
I'm reading through the docs and the examples, and attempting to replicate my own simple version, but most of the examples and tutorials seem to use WebauthnBuilder and prelude in webauthn_rs, but I can't find any mention of them existing or ever having existed in the docs. Am I missing something?

**Comment by benwis** [comment]
Ah, I see what's happening here, the last release was in Dev 21 and all these things were added since then. Not sure what the release schedule is, but I'd love to see one come out so we don't have to target the repo

**Comment by Firstyear** [comment]
@benwis Currently we're in the last stages of "working out" the look of the webauthn-rs api but I wouldn't export more than a few months at most for the next release.

**Comment by Firstyear** [comment]
I might publish a "dev version" to crates.io to help though.

**Comment by Firstyear** [comment]
If you have any feedback at all, I'd love to hear how we can make the library better!

**Comment by benwis** [comment]
Happy to contribute. I should ask about all the webauthn_rs_core imports in the demo site, is everything needed for that available via webauthn-rs too?

**Comment by Firstyear** [comment]
Ahhhh no. have a look at: https://github.com/kanidm/webauthn-rs/tree/master/tutorial 

The "demo site" is for all the edge cases and compat testing and needs access to some of the "unsafe parts" of the library for the conditional UI and compat tests. You can see it "live" here: https://webauthn.firstyear.id.au/

**Comment by benwis** [comment]
Ah, I did not make that distinction, I thought the demo-site was just more fleshed out. I'll use the tutorial instead. Thanks for the tip!

**Comment by Firstyear** [comment]
Perhaps I should rename it from demo site to compat tester or something to prevent confusion?

**Comment by Firstyear** [comment]
@benwis https://crates.io/crates/webauthn-rs/0.4.1-beta.2

**Comment by Firstyear** [comment]
Just beware that the api might change "a little" from here, but not much. Mainly around attestation CA's and device trust enforcement. But that's about the last thing before a full release.

**Comment by benwis** [comment]
No worries, that's what happens with betas. Thanks for heads up!
