### ISSUE TITLE
Possible stricter security check credential counter

### ISSUE THREAD

**Issue by AdroidNavi** [kanidm/webauthn-rs#170]
Correct me if I'm wrong, but I was looking at the code and came across this line.

https://github.com/kanidm/webauthn-rs/blob/b53ddfe4770dd34abad3d86512099e4671186c50/webauthn-rs-core/src/core.rs#L1019

Wouldn't it be fair to assume that if the counter of a credential once had a value above 0 (as persisted on the server) it should not be possible for a subsequent request to have the counter be 0 again.

If that assumption is correct maybe this check can be a bit stricter by removing the `|| cred.counter > 0` check?

**Comment by AdroidNavi** [comment]
Nevermind, I red it wrong, it is actually stricter than what I proposed...

**Comment by Firstyear** [comment]
No problem, thanks for reviewing! Yeah the check is quite strict intentionally :) if you find anything else, feel free to open an issue to discuss!
