### ISSUE TITLE
Removal of Serialize and Deserialize making life harder for DB storage

### ISSUE THREAD

**Issue by benwis** [kanidm/webauthn-rs#184]
Hi,
So in [this PR](https://github.com/kanidm/webauthn-rs/commit/463b5904388b25f4408f409810d3a37186195d57) you remove Serialize and Deserialize derivations for PasskeyAuthentication and PasskeyRegistration, which is great for making it harder for people to store it client side, but kill my ability to convert them to JSON and store them in the DB. We're using server side DB sessions tied to a session key stored in a client side cookie.

Is that an insecure way to do it? If not, can we get those back. The warnings are great though.

**Comment by Firstyear** [comment]
If you have a look at the list of features on the main docs, you'll see this section :) 

https://docs.rs/webauthn-rs/0.4.5/webauthn_rs/index.html#allow-serialising-registration-and-authentication-state

I hope that helps!

**Comment by benwis** [comment]
Ugh, missed the addition of that section. Thanks!

**Comment by Firstyear** [comment]
No stress mate, happy to help :)
