### ISSUE TITLE
Finish support for x5c attestation in packed

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#22]
This was started as part of getting ios+5ci support working, however it is blocked on https://github.com/sfackler/rust-openssl/pull/1095  as we need to access cert extensions and oids to complete the process.

**Comment by agrinman** [comment]
what is missing here for attestations? it seemed like packed format worked for me when i tested it.

**Comment by Firstyear** [comment]
Yes packed works, but there are a number of verification paths I recall that are not yet checked. But as mentioned, this is blocking on being able to read some details on certs that is blocked by rust-openssl :(

**Comment by madwizard-thomas** [comment]
What do you think about using [x509_parser](https://docs.rs/x509-parser/0.9.2/x509_parser/)? If you want to switch to ring/webpki in the future (which I think is doable even with the curve coordinate issues you mentioned), those library have even worse support for reading x509 certificates.

**Comment by Firstyear** [comment]
@ericmarkmartin ^ what do you think about x509 parser here?

**Comment by ericmarkmartin** [comment]
seems solid---I can hack around with it and see how it goes. frustrating that rust openssl hasn't stepped up here

**Comment by Firstyear** [comment]
Yeah :( 

But this also isn't a super important area of the code - webauthn attestation only tells you the manufacturer / trustworthiness of a credential. More important is that we have any cryptographic authentication at all, so the majority of deployments honestly are unlikely to care about attestation. So there's no rush :)

**Comment by Firstyear** [comment]
Complete!
