### ISSUE TITLE
Documentation doubt

### ISSUE THREAD

**Issue by dili91** [kanidm/webauthn-rs#240]
👋 First of all thanks for this repo and the top quality docs. I'm dipping my toes into the WebAuthn and Secure Payment Confirmation topics and having practical samples including thoughtful comments like yours is really helpful. 

I have a doubt on [this](https://docs.rs/webauthn-rs/latest/src/webauthn_rs/lib.rs.html#410) sample though. What do you mean here by _trusted manufacturers_ in this particular context and how the samples at line `410` really differs from the one at `399` ? is that a leftover perhaps ?

**Comment by Firstyear** [comment]
Ahhh yes. That's a left over because I'm currently in the middle of reworking the attestation lists. If you want to remove lines between 408 and 417 in a PR that would be wonderful :)
