### ISSUE TITLE
Remove insecure rs1 flag

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#245]
I think we should remove the insecure rs1 flag. This is currently disabled by default. 

Currently insecure rs1 does NOT allow authenticator public keys that use SHA1. What the flag does is allow attestation CA's that sign with SHA1 to be used. 

SHA1 is considered broken, and NIST now recommends against it's use. Most major CA's also are not allowed to use it.

Disabling this will *only* impact individuals using both attestation *and* authenticators that have a CA signed with SHA1. Since our current support around attestation is still evolving (though getting closer to something I'm happy with) I believe this will not have impacts on most users. 

The risk of allowing the flag to continue is extended use of authenticators signed with CA's that are may potentially be able to have their attestations forged. Since the use of attestation is primarily for high-assurance environments, this is the kind of risk that should be considered by those deployments.

**Comment by yaleman** [comment]
>  Disabling this will only impact individuals using both attestation and authenticators that have a CA signed with SHA1.

I'd hope noone's using a CA signed with SHA1 at this point - sounds like a good scream-test situation - if someone does run across one they can make a *really* good case to add it back as a feature flag maybe.

**Comment by Firstyear** [comment]
There are a number of older windows hello tpm's that use this, but most newer TPM's do not. This is why I think it's likely to not be a widespread problem
