### ISSUE TITLE
Tutorial on android does not work

### ISSUE THREAD

**Issue by timvw01** [kanidm/webauthn-rs#248]
I compiled the unmodified tutorial project, with the axum server. On a desktop it works (great!), when opening the site with an android device the following happens:

Open site
Enter username
Hit Registration
The three dots show
Then it hangs and the browser gives the following error:

```
wasm.js:809 Uncaught (in promise) Error: Unable to create promise
    at imports.wbg.__wbindgen_throw (wasm.js:809:15)
    at wasm_bg.wasm:0x48607
    at wasm_bg.wasm:0xbba9
    at wasm_bg.wasm:0x13a70
    at wasm_bg.wasm:0x32de6
    at wasm_bg.wasm:0xef9b
    at wasm_bg.wasm:0x3fc70
    at wasm_bg.wasm:0x330b4
    at wasm_bg.wasm:0x47efb
    at __wbg_adapter_51 (wasm.js:251:10)
```

I will investigate more, anyone run into this before?

Branch: Master
Commit: 696a7b003891690452d112ba8698055814dd5987

Server running on windows 10
Webpage running on Android 13

**Comment by timvw01** [comment]
I think i found my mistake:

Error was coming from wasm/lib.rs : 
```
// Create a promise that calls the browsers navigator.credentials.create api.
        let promise = window()
            .navigator()
            .credentials()
            .create_with_options(&c_options)
            .expect_throw("Unable to create promise");
```

I think the error comes from the id requiring localhost vs the android requesting @ 192.168.0.xxx.

Too fast to post an issue, my apologies! This can be closed.

**Comment by Firstyear** [comment]
No problem, I think the error could be a bit clearer though. I think the console should have logs about that fault though?

**Comment by timvw01** [comment]
The error shown in the comment above comes from the console and is the only indication of what goes wrong. In hindsight, i could have found the error in the code based on the "Unable to create promise". Still learning :) Great package!

**Comment by Firstyear** [comment]
@timvw01 Thanks so much, if you have any other issues or questions, please let us know :)
