### ISSUE TITLE
Where is the source code for 0.2.0?

### ISSUE THREAD

**Issue by D1plo1d** [kanidm/webauthn-rs#26]
Looking at Github the project was updated to 0.2.0 in the last day (hooray!) but this git repo hasn't been changed since May(?).

Where can I find the source code for the 0.2.0?

**Comment by Firstyear** [comment]
Ahh it's in master, but I didn't tag it properly. I'm starting to improve my release workflows so I missed this. I've just pushed v0.2.1 with cargo-release now, and I'll use that from now on to keep everything in sync. Sorry about that.
