### ISSUE TITLE
Detect keys that may have command stuffing in credid

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#263]
Nitrokeys/Solokeys allow command stuffing in their credential ID. We should warn in the compat test if this is the case (since in the solokey case they may not be identifiable via attestation due to custom certs.

**Comment by micolous** [comment]
Context: https://update.nitrokey.com/ https://update.solokeys.com/

There are a bunch of firmware commands which can be accessed via GetAssertion requests, which do not require user presence.

It looks like this is officially deprecated for SoloKey, and they're replacing it with USB DFU.

**Comment by Firstyear** [comment]
I wonder what the nk3 does here?

**Comment by Firstyear** [comment]
I'm not sure we need this given that we just plan to deny these via attestation anyway?

**Comment by Firstyear** [comment]
I think we don't need this, given we now support attestation and users can just deny nitrokeys.
