### ISSUE TITLE
allow_credentials requirement seems too strict for autofill/conditional UI(?)

### ISSUE THREAD

**Issue by videah** [kanidm/webauthn-rs#268]
I'm currently trying to implement [autofill/conditional UI](https://web.dev/passkey-form-autofill/) on my web service but I've ran into a snag as webauthn-rs always expects a list of credentials to be passed to `start_passkey_authentication` and then later `finish_passkey_authentication` verifies that the credential used to authenticate is part of this list.

Since autofill requires a challenge to be provided by the server ASAP on page load, it's not possible to know who the user is and list their credentials. [The Webauthn spec states allowCredentials can be empty/undefined for this purpose](https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials). 

Currently I don't see a way to make autofill work because `finish_passkey_authentication` will always return `WebauthnError::CredentialNotFound` as it expects the list to be populated. Is there something I'm missing on my end?

I only know a little about Webauthn and this crate so please be gentle if I'm missing something obvious!

**Comment by Firstyear** [comment]
Hey there! If you have a look, there is code to support conditional UI aka discoverable credential auth here: https://github.com/kanidm/webauthn-rs/blob/master/webauthn-rs/src/lib.rs#L1033

The reason it's still behind a feature flag is that firefox doesn't support it, chrome is still developing their credential management ui, and there are some other issue with conditional ui and the experience for users.

In the future once we are happy that it works, keys that have already been registered with "start_passkey_registration" will automatically start to work with "start_discoverable_authentication" and conditional ui. 

As an RP it's also super important to point out that a working flow *without* discoverable credentials is important to have working too! Security keys often have low limits on discoverable credentials, so you will always need to support non-discoverable / non-mediated flows.

Hope that helps!

**Comment by Firstyear** [comment]
PS: @videah If you have any more questions, please let us know :)
