### ISSUE TITLE
Upgrading Base64 (would require MSRV bump to 1.57.0)

### ISSUE THREAD

**Issue by Mythra** [kanidm/webauthn-rs#278]
**Is your feature request related to a problem? Please describe.**

webauthn-rs is the last crate in my workspace that has not yet been upgraded to the latest version of base64. Unfortunately, the new base64 requires a MSRV of rust 1.57 (released December 2nd, 2021). This is much newer than our current MSRV (1.45.0 released July 16th, 2020).

I am opening this issue to describe if it's okay to bump MSRV to 1.57 as a result, and open that pr. To make it clear in Ubuntu the latest package available for bionic is 1.61.0: https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=rust , which seems to be what we actually are testing on (though that may just be because that's all github offers :) ): https://github.com/kanidm/webauthn-rs/blob/master/.github/workflows/ci.yml#L21-L23 .

I will say mention (just cause it's the most common OS brought up when talking about bumping MSRV), this will break debian bullseye (stable), which is using rust 1.48.0 (https://packages.debian.org/bullseye/rustc). Although debian bookworm (testing), sid (unstable), and experimental (rust) are all past this the MSRV of 1.57.0.

**Describe the solution you'd like**

I'd like to be able to update base64 in webauthn-rs, which would require bumping the minimum supported rust version to 1.57.0.

**Describe alternatives you've considered**

If we don't want to bump MSRV that absolutely makes sense, but it would be nice to know when we can bump MSRV.

**Comment by Firstyear** [comment]
I'm happy to increase the MSRV :) The PR would be most welcome. Generally I think we use the base64urlsafedata wrapper as the main place where base64 operations occur.

**Comment by Firstyear** [comment]
Just be sure to add yourself to the contributors file in the process :)
