### ISSUE TITLE
Depends on old version of lru

### ISSUE THREAD

**Issue by RalfJung** [kanidm/webauthn-rs#31]
This crate depends on an old version of lru, which might stop working as the compiler is better able to detect soundness problems (https://github.com/rust-lang/rust/pull/71274). Would be great if you could update the dependency to the latest version. :)

**Comment by Firstyear** [comment]
All good I will update this as soon as I can. Probably on the upcoming weekend. I'm going to have a run through all my crates with cargo outdated, and it's becoming part of my release workflows too. 

Thanks for letting me know!

**Comment by Firstyear** [comment]
Actually found some spare time, resolved with release v0.2.4

**Comment by RalfJung** [comment]
Thanks for the quick fix. :)
