### ISSUE TITLE
Webauthn Service not accessible outside docker

### ISSUE THREAD

**Issue by rainfall-rakesh** [kanidm/webauthn-rs#314]

**Comment by Firstyear** [comment]
This dockerfile is for the compat tester on https://webauthn.firstyear.id.au/

It has no other relation to the service or examples.

You should be testing with the examples if you want to use this library.

**Comment by rainfall-rakesh** [comment]
Thanks for reply.. Which examples you are referring to?

**Comment by rainfall-rakesh** [comment]
Is there any discussion forum where I can post questions?

**Comment by rainfall-rakesh** [comment]
That would have been super easy :-).. I don't see the discussion tab though... Is it access controlled?

![image](https://user-images.githubusercontent.com/103760315/234516107-25d4cd63-131a-476b-98d9-adb5c57f9ee2.png)

**Comment by Firstyear** [comment]
> Is there any discussion forum where I can post questions?

What are you  trying to achieve? There are a lot of docs on https://docs.rs/webauthn-rs/latest/webauthn_rs/ and examples in https://github.com/kanidm/webauthn-rs so im confused what you are trying to do here.

**Comment by rainfall-rakesh** [comment]
Our objective is to setup this webauthn service as docker container and integrate it later with iOS and Android clients later..  

I am able to run service outside of container by following steps in README.md .. 

cd compat_tester/webauthn-rs-demo
cargo run

If I create docker image which does this, service is not accessible out side container.. so I am just trying to make it work...  

Now I am just wondering if this is right approach or not?  I simply want to containerize the webauthn server piece...

Hope it clarifies the requirement?

**Comment by Firstyear** [comment]
> Now I am just wondering if this is right approach or not?

This is not the right approach - the dockerfile is for a *demonstration website* with a *compatability tester*.

There is no examples, no dockerfile from this library you can just magic into production and have it work.

This is a library that you need to understand and include in your own application and your own system design.

You need to build your own site or service that stores credentials for users.

**Comment by rainfall-rakesh** [comment]
This helps. Thank you for response.
