### ISSUE TITLE
compilation errors in crate `webauthn-rs`

### ISSUE THREAD

**Issue by DrewMcArthur** [kanidm/webauthn-rs#334]
### I did this
pulled up a project depending on webauthn-rs (that compiled last week, i thought), and ran `cargo check`

### I expected the following
a clean compilation

### What actually happened
```
 % cargo check                                              
    Checking webauthn-rs v0.4.8
error[E0412]: cannot find type `DeviceKey` in this scope
   --> /Users/drewmca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webauthn-rs-0.4.8/src/interface.rs:460:11
    |
460 | impl From<DeviceKey> for Credential {
    |           ^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
460 | impl<DeviceKey> From<DeviceKey> for Credential {
    |     +++++++++++

error[E0412]: cannot find type `DeviceKey` in this scope
   --> /Users/drewmca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webauthn-rs-0.4.8/src/interface.rs:461:17
    |
461 |     fn from(dk: DeviceKey) -> Self {
    |                 ^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `DeviceKey` in this scope
   --> /Users/drewmca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webauthn-rs-0.4.8/src/interface.rs:467:27
    |
467 | impl From<Credential> for DeviceKey {
    |                           ^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeviceKey` in this scope
   --> /Users/drewmca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webauthn-rs-0.4.8/src/interface.rs:470:9
    |
470 |         DeviceKey { cred }
    |         ^^^^^^^^^ not found in this scope

error[E0616]: field `cred` of struct `interface::Passkey` is private
   --> /Users/drewmca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webauthn-rs-0.4.8/src/lib.rs:496:46
    |
496 |         let creds = creds.iter().map(|sk| sk.cred.clone()).collect();
    |                                              ^^^^ private field

Some errors have detailed explanations: E0412, E0422, E0616.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `webauthn-rs` (lib) due to 5 previous errors
```

### Version (and git commit)
`0.4.8`, 
```
webauthn-rs = { version = "0.4.8", features = ["danger-credential-internals", "danger-allow-state-serialisation"] }
```
tried initially with no features, then only credential internals, then with both.

### Operating System / Version
macos M2 - `aarch64-apple-darwin`

### Any other comments
i saw #332, & tried messing around with features.  probably should beef out the CI tests to make sure any/all feature combinations are able to compile.

[here's my full `Cargo.toml` file](https://github.com/DrewMcArthur/lochstep/blob/c0df915e733292c27ab33a80f77348de37e6d8ad/Cargo.toml) - it could have something to do with other dependencies i've added? but the errors don't seem related. 

side note: would be helpful to update tags here when they're pushed to `crates.io`, i see the crate's page points back here, but this repo doesn't have any links to the latest package / release or anything.

anyways, thanks for all your work on maintaining this!

**Comment by yaleman** [comment]
You'd need the feature `resident-key-support` for DeviceKey to be available, according to this:

![Uploading Screenshot 2023-07-23 at 11.40.07 am.png…]()

**Comment by Firstyear** [comment]
@DrewMcArthur Unless you have a very specific use case, you should avoid device-key if possible. It can cause harm to common authenticator models. In addition it is likely we will gate this type in the future behind attestation of which iPhone/Android can't provide reasonable responses to. 

So IMO you should be avoiding this for now :)

**Comment by DrewMcArthur** [comment]
> You'd need the feature `resident-key-support` for DeviceKey to be available, according [to the source](https://github.com/kanidm/webauthn-rs/blob/a73d1ca0def0ebd79846f4568045fb7b8e3163e5/webauthn-rs/src/interface.rs#L394C3-L402C1)
> 

thanks for this - the issue though is that i'm not using DeviceKey anywhere.  i'm not able to compile the library at all; and you can see in the errors ive posted that none come from my own code.

i've put `passkey` functionality behind a feature in my own app, so i'll leave it out for now.

**Comment by Firstyear** [comment]
I think this was raised by someone else recently about the incorrect feature flags? Can you check #333 ?

No by "this" I mean the deviceKey types. The only types in webuathn-rs you should be looking at right now are passkey or securitykey. The types for AttestedPasskey and AttestedResidentKey (formerly Passwordless and DeviceKey) are both currently "in development" since we are still improving our support for FIDO MDS.

**Comment by Firstyear** [comment]
Closing as I believe this issue is already resolved, please let us know if not!
