### ISSUE TITLE
Is there a typo?

### ISSUE THREAD

**Issue by DnaBoss** [kanidm/webauthn-rs#381]
Whether using the official kits for iOS or Android, the error received is:

Error("unknown variant cable, expected one of usb, nfc, ble, internal, hybrid, test", line: 1, column: 118))

The original request specified transports: ["internal", "cable"]

Does "cable" refer to "ble"? Should "ble" be replaced with "cable"?

**Comment by yaleman** [comment]
Nope, it's the clients sending the wrong thing - this is handled in a recent patch - ref https://github.com/kanidm/webauthn-rs/issues/364

https://w3c.github.io/webauthn/#enumdef-authenticatortransport

**Comment by Firstyear** [comment]
Relates to #386 - we need to do a release soon
