### ISSUE TITLE
Verifying CredentialID has not been previously registered and updating credential

### ISSUE THREAD

**Issue by zacknewman** [kanidm/webauthn-rs#401]
According to [`finish_securitykey_registration`](https://docs.rs/webauthn-rs/latest/webauthn_rs/struct.Webauthn.html#method.finish_securitykey_registration), "You MUST assert that the registered credential id has not previously been registered. to any other account." Is this only true if one did not pass `exclude_credentials` into [`start_securitykey_registration`](https://docs.rs/webauthn-rs/latest/webauthn_rs/struct.Webauthn.html#method.start_securitykey_registration)? If not, what's the point of passing `exclude_credentials` if you always have to check when registration is finished? Additionally, "to any other account" means any account associated with the user UUID, correct? Or does it mean one has to check every `CredentialID` for every user UUID?

[`update_credential`](https://docs.rs/webauthn-rs/latest/webauthn_rs/prelude/struct.SecurityKey.html#method.update_credential) never returns `Some(false)` when [`needs_update`](https://docs.rs/webauthn-rs/latest/webauthn_rs/prelude/struct.AuthenticationResult.html#method.needs_update) returns `true`, correct? Asked more formally, does the following logical biconditional hold:

(∃ `key` | `key.update_credential(res).unwrap()`) ⇔ `res.needs_update()`

**Comment by Firstyear** [comment]
You need to check it's not registered to *any other users accounts* and we don't have visibility into that. We can only see what's excluded from *this* users account.

**Comment by Firstyear** [comment]
Also I can't read that formal math syntax, so I don't know what it means.

**Comment by Firstyear** [comment]
> > You need to check it's not registered to _any other users accounts_ and we don't have visibility into that. We can only see what's excluded from _this_ users account.
> 
> So if `exclude_credentials` contains _all_ `CredentialID`s from _all_ user UUIDs

You are misunderstanding.

Exclude_credentials is only *this* users credentials, to stop the situation where the user has say two yubikeys connected. If one is enrolled and the other is about to be enrolled, it disables the *already enrolled key* from proceeding, and then we double check that in the registration process.

> , does one still have to verify that the `CredentialID` is not used after calling `finish_securitykey_registration`? If so, then passing `exclude_credentials` seems to not serve any purpose since all of the work that went into creating `exclude_credentials` needs to be happen again after calling `finish_securitykey_registration`.

Then afterwards, you need to check "okay, is this credential ID reused by any other users". That's why it's separate.

**Comment by Firstyear** [comment]
If you already have a way in the database to enforce that credential ID is unique, then you have already satisfied this requirement, yes.

**Comment by Firstyear** [comment]
exclude credentials has size limits on some authenticators. Remember, exclude credentials *is transmitted in the registration to the users browser*. 

Also when you have 100,000 users, they each enroll two credentials, then you just sent 200,000 credentials to a user for every registration. That's going to cause problems no matter how you cut it. 

I think you need to consider exclude_credentials as a *ui hint* to help guide one user to not duplicate a credential. And then the actual check for uniqueness is enforced later.

**Comment by Firstyear** [comment]
You have to sent exclude credentials *so that the users browser doesn't try to register the same security key twice*. That's what it's for.

So you have to use it to make sure the users experience is a good one. Then you do the uniqueness check after.

**Comment by Firstyear** [comment]
> You have to sent exclude credentials _so that the users browser doesn't try to register the same security key twice_. That's what it's for.

And when I say this, I mean there is actually specific logic in browsers to *disable* credentials in the excluded credentials list so they don't trigger during registration.

**Comment by Firstyear** [comment]
> I understand that when the browser receives `excluded_credentials` it won't use any of those credentials (modulo bugs); however it's not sufficient to only disable those credentials since all credentials by all users need to not be registered. So it's kinda pointless.

No, it's not.

You are setting exclude credentials so that in the *majority* case, most users will have their UI guided to help them select and enroll the right credential. 

And then if a malicious person was trying to register a duplicate credential, it's caught post registration with a "hey, maybe you shouldn't do that".

You are looking at this only from the simple view of "exclude is about excluding all these things to enforce uniqueness". It's not. It's there to help users experience to make sure that in the "happy path" they get a good experience, and then the application still can enforce the stricter rule later.

**Comment by Firstyear** [comment]
I have two yubikeys. I register the first. Now I go to register the second.

exclude_credentials is set to exclude the first key. Now only my second key activates. It means I don't accidentally re-enroll the first key. 

That's what it's for.

**Comment by Firstyear** [comment]
Why are you thinking about this like odds? Like it's statistics? You're approaching this in the completely wrong way. 

Imagine you have someone where they have two yubikeys are connected, they are both blinking. maybe they are elderly. Maybe they're in a rush. Maybe they got an sms from someone. Humans are human, they are distracted. Who knows.  They look at their keys. Which one do they press? They know they just enrolled one, but now they are both blinking? What do they press now? Why are they both lit up? They're confused, they then accidentally press the first key again. They get a weird error they don't understand and it confuses them. They don't know what they did wrong. They get annoyed, and have to repeat the process and they try again. 

All this could be easily avoided, if during the registration only *one key lights up*. They know exactly what to press and interact with. It's unambiguous. It helps them have a better experience. It guides the person to the right action. 

This is about human interaction, it's about empathy with others, it's about making sure that we give people a good, clear, and helpful experience.

**Comment by Firstyear** [comment]
Yes that's exactly what I've been saying the whole time.

**Comment by Firstyear** [comment]
And if the keys DO light up incorrectly, that's a browser bug - not a webauthn-rs bug.

**Comment by Firstyear** [comment]
> You were not clear.

https://github.com/kanidm/webauthn-rs/issues/401#issuecomment-1861852361

**Comment by yaleman** [comment]
[Mozilla's explanation](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create#excludecredentials) of the client side might help.

> If the create() call is attempting to create a duplicate public key credential on an authenticator, the user agent will guide to user to create the credential using a different authenticator, or fail if that is not possible.

Or perhaps [the w3c discusssion](https://github.com/w3c/webauthn/issues/1235).

We include it because it's part of the spec, not for the fun of it.

**Comment by Firstyear** [comment]
> And what about the code example question?
> 
> ```rust
> use webauthn_rs::prelude::{PublicKeyCredential, SecurityKey, Webauthn};
> fn main() {
>     let mut keys: [SecurityKey; 1]; // Pretend this is instantiated with a `SecurityKey`.
>     let authn: WebAuthn; // Pretend this is instantiated.
>     let (challenge, auth) = authn.start_securitykey_authentication(keys.as_slice()).unwrap();
>     // Send data to client and retrieve response.
>     ⋮
>     let pub_cred: PublicKeyCredential; // Pretend this is instantiated from imaginary response above.
>     let res = authn.finish_securitykey_authentication(&pub_cred, &auth).unwrap();

If an excluded credential was re-used, the line *above* will have an error. 

>     // Is it possible this will `panic`?
>     assert!(!res.needs_update() || key.update_credential(&res).unwrap());
> }
> ```

**Comment by Firstyear** [comment]
needs_update() is triggered if:

* The credentials internal activation counter has increased (applies to all hardware FIDO2 devices)
* If the backup state has changed (may change from false to true on certain classes of software devices like a password manager)

**Comment by Firstyear** [comment]
Which also is why update_credential can return false, because if you dispatch the update events asynchronously, they can become out of order meaning that the counter update doesn't need to apply since the counter is already now greater than the value in the authentication request.

**Comment by Firstyear** [comment]
getTransports is cooked on all browsers. The only reliable way to check transports is with attested passkeys, and we do this already.

**Comment by Firstyear** [comment]
If the credential is attested, the transport will be automatically added, even for security keys. I forgot security key does attestation.

**Comment by Firstyear** [comment]
Nope, shouldn't affect it.

**Comment by Firstyear** [comment]
Transports was only added recently in git master btw.
