### ISSUE TITLE
Conditional compilation of webauthn_rs_core::attestation::verify_attestation_ca_chain

### ISSUE THREAD

**Issue by zacknewman** [kanidm/webauthn-rs#402]
LibreSSL is _mostly_ compatible with OpenSSL 1.1.x; however it is not entirely. In particular there is no `no-check-time` in `openssl-verify`. As a result, `webauthn_rs_core` does not compile due to the `danger_disable_certificate_time_checks`  parameter in `attestation::verify_attestation_ca_chain` which internally relies on `openssl::x509::verify::X509VerifyFlags::NO_CHECK_TIME`. It would be nice if that `bool` were ignored when the OS is one of the *BSDs or macOS.

I understand if the *BSDs and macOS are not supported though. It's not too difficult to maintain a local version of the library with the line removed and relying on a `[patch]` section in `Cargo.toml`.

**Comment by yaleman** [comment]
macOS is totally supported with OpenSSL, Most of the devs use it... but not 1.x normally - [3.x is **required** for webauthn-authenticator-rs ](https://github.com/kanidm/webauthn-rs/blob/142e8d77335cfcd947ecc8610d45a3abfe4cd823/webauthn-authenticator-rs/build.rs#L39). I'm not sure anyone tests with LibreSSL.

**Comment by yaleman** [comment]
Exactly. Note [the openssl docs in the repo](https://github.com/kanidm/webauthn-rs/blob/master/OpenSSL.md).

**Comment by yaleman** [comment]
No worries 😄
