### ISSUE TITLE
Default implementation of `policy_verify_trust` doesn't match documentation

### ISSUE THREAD

**Issue by ericmarkmartin** [kanidm/webauthn-rs#42]
The doc comment above the default implementation of `policy_verify_trust` says

```
/// The default implementation of this method rejects None and Uncertain attestation, and
/// will "blindly trust" self attestation and the other types as valid.
/// If you have strict security requirements we strongly recommend you implement this function,
/// and we may in the future provide a stronger default relying party policy.
```

The implementation, however, appears to accept the `None` attestation type
```
fn policy_verify_trust(&self, at: AttestationType) -> Result<Credential, ()> {
    log::debug!("policy_verify_trust -> {:?}", at);
    match at {
        AttestationType::Basic(credential, _attest_cert) => Ok(credential),
        AttestationType::Self_(credential) => Ok(credential),
        AttestationType::AttCa(credential, _attest_cert, _ca_chain) => Ok(credential),
        AttestationType::None(credential) => Ok(credential),
        _ => {
            // We don't know how to assert trust in this yet, or we just
            // don't trust it at all (Uncertain, None).
            Err(())
        }
    }
}
```

**Comment by Firstyear** [comment]
I think we should update the method not to use a _ =>, but to explicitly list what we accept and reject, and we should probably fix the doc to match. I think we should also allow none by default,

**Comment by ericmarkmartin** [comment]
That makes sense. We could also then distinguish between "We don't know how to assert trust in this" and "we just don't trust it at all" with the error type.

**Comment by Firstyear** [comment]
Well the point of this is that a person can over-ride the default impl to add their own trust rules given the type of attestation presented. But also that's what the Uncertain type is for compared to None/Self. It could be worth allowing a custom error type though for policy verify trust but I don't know how we'd work that in ...

**Comment by ericmarkmartin** [comment]
True---I suppose this will be an issue for another day. The fix here, however, seems pretty straightforward so I'll try to throw a PR up later tonight.
