### ISSUE TITLE
CredProps::rk should be public

### ISSUE THREAD

**Issue by smessmer** [kanidm/webauthn-rs#421]
**Is your feature request related to a problem? Please describe.**
Because of issues with the webauthn-rs serialization discussed in other Github issues, we're using our own custom serialization logic for passkeys. This means we serialize our own custom types and need access to the internals of the passkey struct so we convert from/to our own custom types. We do have access to most, but `CredProps::rk` is a field that we don't have access to. It is accessible from a passkey via the `Credential::extensions` property.

**Describe the solution you'd like**
Make `CredProps::rk` public

**Describe alternatives you've considered**
Ideally, we wouldn't have to do our own custom serialization logic, i.e. webauthn-rs would itself have a space-efficient and backwards compatible serialization layout. But until that's the case, this way works for us.

**Comment by Firstyear** [comment]
I was thinking we need to address the serialisation side soon. @micolous We should catch up and resolve this once and for all.
