### ISSUE TITLE
Dependency on old compact_jwt revision

### ISSUE THREAD

**Issue by bernharddick** [kanidm/webauthn-rs#443]
**Is your feature request related to a problem? Please describe.**
Hi, while looking into packaging webauthn-rs for Debian I stumbled upon the dependency on an 0.2.x release of compact_jwt. As the change to 0.3.x and upwards includes breaking API changes (i.e. JwsUnverified no longer being available) it cannot be solved by just relaxing the dependency. So I kindly ask to update the project to build with a recent compact_jwt revision.

**Describe the solution you'd like**
Update dependency to recent version of compact_jwt

**Describe alternatives you've considered**
Co-packaging an old compact_jwt revision is theoretically possible but should be avoided.

**Comment by Firstyear** [comment]
First, you should not be packaging crates for a distro. It goes against how Rust works as a language.

I will update compact_jwt however.
