### ISSUE TITLE
https://webauthn.firstyear.id.au/ reports 503 service unavailable

### ISSUE THREAD

**Issue by sycamoreoak** [kanidm/webauthn-rs#467]
### I did this

visit https://webauthn.firstyear.id.au/ in my browser

having a working demo can be nice for troubleshooting

### I expected the following

awesome webauthn-rs demo

### What actually happened

https://webauthn.firstyear.id.au/ reports 503 service unavailable

### Operating System / Version
yes

### Any other comments
🎄

**Comment by phuang-hive** [comment]
same thing happening to me

**Comment by Firstyear** [comment]
resolved now. This issue was caused by fido releasing updates to their MDS without notification or related documentation updates, which stopped us being able to actually test attestation safely.
