### ISSUE TITLE
UV=true should be accepted when discouraged

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#48]
According to the L2 version of webauthn, "If user verification is required for this assertion, verify that the User Verified bit of the flags in authData is set.". We currently reject authentication/registration if discouraged has UV=true, which is incorrect. We should allow this.

Additionally, we should check that UV || UP == true, as UV implies UP and I think some authenticators only set one or the other.

**Comment by Firstyear** [comment]
Rereading the spec, authenticators must always set UP even if UV is true, so this can be ignored.

**Comment by agrinman** [comment]
I think this can be closed UV=true is accepted correctly (even when policy is discouraged).
