### ISSUE TITLE
Be more tolerant to changes in CCD

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#52]
https://www.w3.org/TR/webauthn-2/#dictionary-client-data

This will change in the future to include crossOrigin, so we must be ready for this to occur and handle it.

**Comment by ericmarkmartin** [comment]
A quick test indicates that chromium already sends crossOrigin, whereas Firefox does not

**Comment by ericmarkmartin** [comment]
We could either add a field `pub cross_origin: Option<bool>` so that we can capture the value from browsers that send it, or we can add a `BTreeMap` or `HashMap` to capture unknown keys, wait until `cross_origin` is better adopted, and then add it as `cross_origin: bool`.

**Comment by Firstyear** [comment]
I think doing it with Options makes more sense :)

**Comment by Firstyear** [comment]
This seems to be resolved :)
