### ISSUE TITLE
Should relying party origin check include port?

### ISSUE THREAD

**Issue by ElArtista** [kanidm/webauthn-rs#53]
This check https://github.com/kanidm/webauthn-rs/blob/master/src/core.rs#L297 compares the client data origin with the relying party config origin. I've bumped into the scenario where the check fires when the webauthn frontend listens on a different port than the backend. Should the check include the port, or should this be host only? (Browser/Client seems to send the port in clientData)

**Comment by Firstyear** [comment]
Hi there,

I think that from having implemented webauthn-authenticator-rs and inspecting the content of other libraries, I think the port is not included in origin. Which browser and client are you using? As well, which version of webauthn-rs are you using?

**Comment by Firstyear** [comment]
I have found this and resolved it in 0.3 recently

**Comment by ElArtista** [comment]
Nice! I haven't managed to continue my webauthn personal project yet due to missing time, but I'll try to check the fix out!
