### ISSUE TITLE
Support credProtect and credBlob

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#55]
https://fidoalliance.org/specs/fido-v2.1-rd-20210309/fido-client-to-authenticator-protocol-v2.1-rd-20210309.html#sctn-credProtect-extension

**Comment by ericmarkmartin** [comment]
With #56 and #66 merged, should we close this? There's more to do, but such tasks are perhaps better captured by smaller issues like #67.

**Comment by Firstyear** [comment]
Yep, I think so :)
