### ISSUE TITLE
Visibility issue with Challenge newtypes

### ISSUE THREAD

**Issue by hgzimmerman** [kanidm/webauthn-rs#64]
I made a mistake when declaring the privacy on the `Challenge`'s wrapped byte vector in a recent refactor. It is currently possible to put a `Vec<u8>` into the `Challenge` wrapper, but it is not possible to get it out again.

The two solutions to this are to make the inner type `pub` again, or to offer a `fn into_inner(self) -> Vec<u8>` on this type. I prefer the latter.

**Comment by Firstyear** [comment]
Inside the crate we can just use challenge.0 though can't we?

**Comment by hgzimmerman** [comment]
Yes, internally nothing has changed, but Challenge is a type that is exposed publicly, and for whatever reason a user might want to make use of the inner data in the Challenge in a different context (ex: serializing). Currently, the change I've made is a regression, as before the inner byte vector was just `pub`.

**Comment by Firstyear** [comment]
I think that people shouldn't be tampering with the challenges that we generate though, so I'm happy that this is "hidden". There are actually some issues under discussion in the webauthn group about this, and people "mis-using" the challenge field to sign arbitrary data, but it actually weakens the system.

**Comment by Firstyear** [comment]
https://github.com/w3c/webauthn/issues/1595

**Comment by hgzimmerman** [comment]
Interesting. I think that is reasonable. 
I would think that having a public `new(bytes: Vec<u8>)` function would be problematic if we wish to prevent users from placing arbitrary data in the challenge. Perhaps that should be made `pub(crate)` instead?

**Comment by Firstyear** [comment]
Yes, I think so :)

**Comment by hgzimmerman** [comment]
Thanks!
