### ISSUE TITLE
Rename COSE content type to algorithm

### ISSUE THREAD

**Issue by madwizard-thomas** [kanidm/webauthn-rs#74]
Moved from #73:
> Some other minor things I came across is COSEContentType: this is called COSE algorithm in WebAuthn and COSE specs. Also ECDSA_SHA256/ECDSA_SHA384/ECDSA_SHA512 are called ES256, ES384 and ES512 in the specs.

The algorithm simultaneously defines the message digest algorithm (e.g. SHA256) and the signature algorithm (ECDSA, EDDSA, RSA-PSS, etc.). Implicitly this also restricts things like the type of key and curve used.

**Comment by Firstyear** [comment]
I think this is resolved
