### ISSUE TITLE
Migrating credentials from U2F

### ISSUE THREAD

**Issue by dani-garcia** [kanidm/webauthn-rs#76]
I'm in the process of migrating a [web server](https://github.com/dani-garcia/vaultwarden) using [U2F](https://github.com/wisespace-io/u2f-rs) to Webauthn using this crate, and while new Webauthn registrations have been working great in my limited testing, I've hit a snag migrating existing U2F registrations to the new Webauthn format:

Some snippets of the code I used for this migration are:
```rust
/// Migrating the credentials saved in the database

use u2f::register::Registration;
use webauthn_rs::proto::*;

let reg: Registration = get_user_registration();

let x: [u8; 32] = reg.pub_key[1..33].try_into().unwrap();
let y: [u8; 32] = reg.pub_key[33..65].try_into().unwrap();

let cred = COSEKey {
    type_: COSEContentType::ECDSA_SHA256,
    key: COSEKeyType::EC_EC2(COSEEC2Key {
        curve: ECDSACurve::SECP256R1,
        x,
        y,
    }),
};

let new_reg = Credential {
    counter: reg.counter,
    verified: false,
    cred: cred,
    cred_id: reg.key_handle.clone(),
};
```

```rust
/// Setting the appId extension to allow migrated credentials to be recognized
let mut ext: BTreeMap<String, String> = BTreeMap::new();
ext.insert("appid".into(), "https://domain.tld/app-id.json".into());
let (response, state) = webauthn.generate_challenge_authenticate_extensions(creds, Some(ext))?;
```

The problem I'm encountering right now is trying to authenticate with this credential will cause an `InvalidRPIDHash` error inside the `verify_credential_internal` function:
https://github.com/kanidm/webauthn-rs/blob/ee6575188884f6663ba5784727fe67daf93a619a/src/core.rs#L589
Because the webauthn config will be setup with a RP like `domain.tld` while the clients using these migrated credentials will send the U2F AppId hash for `https://domain.tld/app-id.json`. Simply commenting that check out made it work for me, but it's probably not a good idea to remove that entirely.

Is it possible to add some optional compatibility mode to this crate so it can check the U2F AppId as well as the Webauthn RP? Is there any other solution I'm not seeing right now? I'm not very knowledgeable on either U2F or Webauthn, so maybe I'm missing something.

Thanks!

Edit: The exact crate versions I'm using:
```toml
u2f = "0.2.0"
webauthn-rs = "0.3.0-alpha.7"
```

**Comment by agrinman** [comment]
Hey there, it looks like this spec would be the starting place for an implementation of this: https://www.w3.org/TR/webauthn-2/#sctn-appid-extension though I am not sure there is great utility in supporting this.

However, if I were in your shoes I would probably run both webauthn-rs and u2f in parallel and authenticate using the u2f library if it's a u2f key. Any reason why this wouldn't work for you?

**Comment by dani-garcia** [comment]
For my use case, I'm a bit limited by the clients that interact with my server, which are out of my control and have dropped support for U2F and only allow Webauthn now. Migrating the U2F credentials to Webauthn seems like the most straightforward solution I can see at the moment.

For what it's worth, I've made some changes in the master branch to allow this appid support here: https://github.com/dani-garcia/webauthn-rs/commit/671483adadcb27e0f82fb0c593dfefd4d723e386.

**Comment by Firstyear** [comment]
Well, the alternative is you could run two-instances of the WebauthnConfig, one for Webauthn, one for U2F-migrated credentials, which have the relevant RPid configurations. Then you can set an external flag in your data to which class of credential it is, and which WebauthnConfig you should use (and if it needs the extension or not). 

This in mind, I'd be happy to see appid supported as an extension, so feel free to make a PR for early code review so we can discuss the specifics of it there :)

**Comment by dani-garcia** [comment]
I think keeping separate configs might work for my usecase, yeah. I'll let you know if I encounter any issues doing it that way.

I've created the PR here: https://github.com/kanidm/webauthn-rs/pull/78. Let me know if you have any comments or suggestions to improve it.

**Comment by Firstyear** [comment]
@dani-garcia Do you think this issue is resolved now?

**Comment by dani-garcia** [comment]
Yes, this is resolved for me so I'll close it now.
